export WEBSTATS_REDIS_URL="redis://localhost:6379"
export WEBSTATS_BIND=":8080"
export WEBSTATS_COOKIE_SECRET="mytestnonsecret"
export WEBSTATS_PASSWORD_SALT="mytestnonsecretsalt"
export WEBSTATS_ARCHIVE_DATABASE="/tmp/archive.db"
export WEBSTATS_ARCHIVE_MAX_AGE="24h"
