#!/usr/bin/env bash
#
##!/usr//bin/env plash
#--from ubuntu:jammy
#--apt golang gcc libc-dev gcc-x86-64-linux-gnu git
#--layer
#--entrypoint-script
#cd ../backend
#export PATH


cd backend
# exec env GOOS=linux GOARCH=amd64  CC=aarch64-unknown-linux-gnu-gcc CGO_ENABLED=1 \
# go build -a -ldflags '-linkmode external -extldflags "-static"'  -o ../webstats
#
exec env GOOS=linux go build -o ../webstats
