#!/usr/bin/env bash
set -euo pipefail

INPUT_JSON=${1:-static/timezones.json}
OUTPUT_GO=${2:-backend/models/timezones_gen.go}

mkdir -p "$(dirname "$OUTPUT_GO")"

{
  echo 'package models'
  echo ''
  echo '// Code generated by make gen-timezones; DO NOT EDIT.'
  echo ''
  echo 'var OffsetToTimezones = map[int][]string{'
  jq -e -r '.zones
    | sort_by(.minutes)
    | group_by(.minutes)
    | map({m: (.[0].minutes), ids: ([.[].id] | sort | unique)})
    | map("\t\(.m): []string{" + ( .ids | map(@json) | join(", ") ) + "},")
    | .[]' "$INPUT_JSON"
  echo '}'
} > "$OUTPUT_GO"

echo "Written $OUTPUT_GO"
