--- 
name: Deploy app
on:
  push:
    branches:
      - master
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        env: 
          SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
        name: "Create SSH key"
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
            sudo chmod 600 ~/.ssh/private.key
        shell: bash

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      -
        name: "Use python"
        uses: actions/setup-python@v2

      -
        name: "Install pelican"
        run: pip3 install pelican Markdown

      -
        name: "Install jinja markdown tag"
        run: pip3 install jinja_markdown

      -
        name: "Install yasha"
        run: pip3 install yasha

      -
        name: "make all"
        run: make all
      
      -
        name: "push to github pages"
        run: |
          set -x
          git config --global user.email "hey@counter.dev"
          git config --global user.name "Counter"
          mv out/* static
          cd static
          git init
          git remote add origin "git@github.com:ihucos/counter-staging-static.git"
          echo 'staging.counter.dev' > CNAME
          touch .nojekyll
          git add .
          git commit -m "deploy"
          GIT_SSH_COMMAND="ssh -i ~/.ssh/private.key" git push origin -f HEAD:gh-pages
